### ISSUE TITLE
Error while handling OAUTH service UI on the login screen

### ISSUE THREAD

**Issue by rkorn86** [apereo/cas#2398] opened 2017-02-20 13:59 UTC
I guess this is a regression of https://github.com/apereo/cas/issues/2120 and https://github.com/apereo/cas/commit/71a69e231fd874672d40e05877a51144d9109159.
Currently on 5.1.0-RC2-SNAPSHOT oAuth services are displayed as RegexRegisteredService, which means the "OAuth Authentication Callback Request URL" is used for displaying the service UI. I tested this with Google OAuth Playground.

**Comment by rkorn86** [comment] 2017-02-20 14:58
In addition: the completely wrong registered service is used (the callback service and not the oauth service) for attribute releasing and so on

**Comment by mmoayyed** [comment] 2017-02-20 16:47
Looks like the issue is with the construction of callback urls where query parameters are always wrongly and statically checked against a `client_id`

**Comment by mmoayyed** [comment] 2017-02-20 16:47
Closed via https://github.com/apereo/cas/commit/e51d0d25185984aaabce6b3a59cc25538a25bdab#diff-7ecf3d3dfb93a5b04bf174036940b697L31

**Closed by mmoayyed** 2017-02-20 16:47 UTC
Labels: Bug, Minor, OAuth, User Interface
