### ISSUE TITLE
Google Apps Web Flows: "successWithWarnings" event is not recognized

### ISSUE THREAD

**Issue by petracvv** [apereo/cas#2531] opened 2017-04-14 18:47 UTC
Using CAS 5.0.4 and tomcat 8.5.11 as the webserver

I am using the cas-server-support-ldap and cas-server-support-saml-googleapps plugins to get SSO for our Google Apps accounts in CAS with the LDAP backend. We have the ldap password policy turned on. Whenever I try to log in to our Google Apps instance with an account with a password near expiration, after the password warning is presented in CAS the continue button produces a 400 error (though it appears this error is on the google side not the CAS side). 

Looking in the logs with webflow debug on I see messages like this:
```2017-04-14 13:28:00,648 DEBUG [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] - Located ticket-granting ticket in the context. Retrieving associated authentication
2017-04-14 13:28:00,649 DEBUG [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] - Resulting authentication matches the authentication from context
2017-04-14 13:28:00,649 DEBUG [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] - Resulting authentication matches the authentication from context
2017-04-14 13:28:00,651 DEBUG [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] - Resolved single event [successWithWarnings] via [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] for this context
2017-04-14 13:28:00,651 DEBUG [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] - Resolved single event [successWithWarnings] via [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] for this context
2017-04-14 13:28:00,652 WARN [org.apereo.cas.web.flow.resolver.impl.RankedAuthenticationProviderWebflowEventResolver] - The authentication context cannot be satisfied and the requested event successWithWarnings is unrecognized
2017-04-14 13:28:00,652 WARN [org.apereo.cas.web.flow.resolver.impl.RankedAuthenticationProviderWebflowEventResolver] - The authentication context cannot be satisfied and the requested event successWithWarnings is unrecognized
2017-04-14 13:28:00,652 DEBUG [org.apereo.cas.web.flow.resolver.impl.RankedAuthenticationProviderWebflowEventResolver] - Resolved single event [error] via [org.apereo.cas.web.flow.resolver.impl.RankedAuthenticationProviderWebflowEventResolver] for this context
2017-04-14 13:28:00,652 DEBUG [org.apereo.cas.web.flow.resolver.impl.RankedAuthenticationProviderWebflowEventResolver] - Resolved single event [error] via [org.apereo.cas.web.flow.resolver.impl.RankedAuthenticationProviderWebflowEventResolver] for this context
```

This does not happen with other services that are using the CAS protocol or a SAML2 service (testshib).

Please let me know if you want more log excerpts or an overlay pushed.

**Comment by mmoayyed** [comment] 2017-04-15 09:10
Thank you for the issue report. This is a duplicate of https://github.com/apereo/cas/issues/2514 which is already applied to master. You're welcome to grab the changes from there and apply them to 5.0.x branch and prepare a pull request.

**Closed by mmoayyed** 2017-04-15 09:10 UTC

**Comment by petracvv** [comment] 2017-04-19 14:39
Ok, I will look into that. However, we are not using Multifactor Auth at all so I'm not sure how a MFA fix would take care of this. I'll try to look through the code and get the gist of what is happening.

**Comment by xavtrix** [comment] 2017-08-23 17:13
@petracvv Did you figure this one out?  We are having the exact same issues with a couple of our applications when we enable this feature.

**Comment by mmoayyed** [comment] 2017-08-23 19:05
@petracvv @xavtrix if you still see this, I recommend you attach a DEBUG log of Spring Webflow so I might be able to spot something.

**Comment by dima767** [comment] 2017-08-23 19:18
I have similar reports from a client. Just adding this comment as a future reminder note...

**Comment by petracvv** [comment] 2017-08-23 20:32
@xavtrix We are currently running CAS version 5.1.0 and I cannot reproduce it on my instance any longer. (At least the issue I originally reported). My password is close to expiring and I can login to our Google Apps going through the password warning page without a problem.

**Comment by xavtrix** [comment] 2017-08-24 19:39
@mmoayyed Hey, Misagh.  See attached logs for when we have the password policy enabled and disabled.

[Password-Policy-Enabled.txt](https://github.com/apereo/cas/files/1250018/Password-Policy-Enabled.txt)
[Password-Policy-Disabled.txt](https://github.com/apereo/cas/files/1250022/Password-Policy-Disabled.txt)
