### ISSUE TITLE
 No EntityManager exception with JpaTicketRegistry, CAS 4.2.2

### ISSUE THREAD

**Issue by siim-romanov** [apereo/cas#1817] opened 2016-06-03 09:35 UTC
1 CAS server version: **4.2.2**
2 Container/environment type/version: **Tomcat 8.0.35, Windows, Java 8**
3 Steps to duplicate the problem

- Deploy cas.war

- Log in with default user casTest::Mellon

- Wait forJPA Ticket Registry cleaning

4 Overlay: https://github.com/cas-projects/cas-issues/tree/master/cas-issue-1817
5 Stacktraces and CAS logs
```
2016-06-03 12:32:38,861 ERROR [org.jasig.cas.ticket.registry.JpaTicketRegistry] - <no transaction is in progress
javax.persistence.TransactionRequiredException: no transaction is in progress
        at org.hibernate.jpa.spi.AbstractQueryImpl.checkTransaction(AbstractQueryImpl.java:205)
        at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:433)
        at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:364)
        at com.sun.proxy.$Proxy88.getResultList(Unknown Source)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicketAndChildren(JpaTicketRegistry.java:120)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicket_aroundBody4(JpaTicketRegistry.java:104)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$AjcClosure5.run(JpaTicketRegistry.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicket(JpaTicketRegistry.java:91)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply_aroundBody0(JpaTicketRegistry.java:287)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$1$AjcClosure1.run(JpaTicketRegistry.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply(JpaTicketRegistry.java:282)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply(JpaTicketRegistry.java:1)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.Iterators.size(Iterators.java:191)
        at com.google.common.collect.Collections2$FilteredCollection.size(Collections2.java:211)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.execute_aroundBody16(JpaTicketRegistry.java:299)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$AjcClosure17.run(JpaTicketRegistry.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.execute(JpaTicketRegistry.java:266)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
>
```

Also in one deployment I got this error
```
2016-05-30 19:40:21,108 ERROR [org.jasig.cas.ticket.registry.JpaTicketRegistry] - Error removing ST-5-7RnrfSjskMvCiYgc7E9d-example.org from registry.
javax.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread - cannot reliably process 'remove' call
 at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:277) ~[spring-orm-4.2.3.RELEASE.jar:4.2.3.RELEASE]
 at com.sun.proxy.$Proxy69.remove(Unknown Source) ~[?:?]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry.removeTicket(JpaTicketRegistry.java:149) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicket_aroundBody4(JpaTicketRegistry.java:99) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$AjcClosure5.run(JpaTicketRegistry.java:1) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjweaver-1.8.6.jar:1.8.6]
 at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44) ~[inspektr-aspects-1.3.GA.jar:1.3.GA]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicket(JpaTicketRegistry.java:91) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply_aroundBody0(JpaTicketRegistry.java:290) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$1$AjcClosure1.run(JpaTicketRegistry.java:1) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjweaver-1.8.6.jar:1.8.6]
 at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44) ~[inspektr-aspects-1.3.GA.jar:1.3.GA]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply(JpaTicketRegistry.java:282) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply(JpaTicketRegistry.java:1) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652) ~[guava-18.0.jar:?]
 at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-18.0.jar:?]
 at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-18.0.jar:?]
 at com.google.common.collect.Iterators.size(Iterators.java:191) ~[guava-18.0.jar:?]
 at com.google.common.collect.Collections2$FilteredCollection.size(Collections2.java:211) ~[guava-18.0.jar:?]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry.execute_aroundBody16(JpaTicketRegistry.java:299) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$AjcClosure17.run(JpaTicketRegistry.java:1) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjweaver-1.8.6.jar:1.8.6]
 at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44) ~[inspektr-aspects-1.3.GA.jar:1.3.GA]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry.execute(JpaTicketRegistry.java:266) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.1.jar:?]
 at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.2.1.jar:?]
```

https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/-G08-1LDiBk

**Comment by dima767** [comment] 2016-06-03 09:52
Is this something @frett has experienced recently. Would you be willing to take a look at this? The overlay to reproduce is located here: https://github.com/cas-projects/cas-issues/tree/master/cas-issue-1817

**Comment by frett** [comment] 2016-06-03 12:18
I saw this behavior on CAS 5.0. It's happening because the registry cleaner process is internal to the JPATicketRegistry bean. So, it makes internal calls to interact with the registry which misses the spring transactional AOP wiring.

**Comment by dima767** [comment] 2016-06-03 13:17
Did we fix it in the master? If so, can we back port that commit to 4.2.x?

**Comment by mmoayyed** [comment] 2016-06-06 14:31
No this isn't fixed in master. I can duplicate it. I'll take a pass today and see if I can clear things up in 4.2.x.

**Comment by mmoayyed** [comment] 2016-06-06 20:11
Going to port forward to master.

**Comment by siim-romanov** [comment] 2016-06-07 09:35
I built from 4.2.3-SNAPSHOT with following additional dependencies versions and cleaning process is now working.
<hibernate.core.version>4.1.0.Final</hibernate.core.version>
<oracle.ojdbc7.version>12.1.0.2</oracle.ojdbc7.version>

**Comment by mmoayyed** [comment] 2016-06-07 11:24
Thanks for the confirmation.

You didnt have to build from source. We build it for you. You should simply point your overlay to 4.2.3-SNAPSHOT

**Comment by siim-romanov** [comment] 2016-06-07 11:29
Sorry for misinformation. Actually I didn't build from source, I did like you said (pointed my overlay). :)

**Comment by mmoayyed** [comment] 2016-06-07 11:31
Excellent. Even better :)

**Comment by mmoayyed** [comment] 2016-06-07 11:34
@frett while porting the changeset over to master, I plan to simplify things a bit via the new @Scheduled annotation and clean up the scheduling process. I'll keep the thread open until it's done, and it would be great if you could review and do some "real" testing when it's all put together.

**Comment by mmoayyed** [comment] 2016-06-23 19:27
Porting over to 5; Closing since this is done for 4.2.x

**Closed by mmoayyed** 2016-06-23 19:27 UTC
Labels: Bug, JDBC/JPA, Major, Ticket
