### ISSUE TITLE
Can't disable LDAP pool validations

### ISSUE THREAD

**Issue by maelstr** [apereo/cas#2316] opened 2017-01-18 12:44 UTC
```
cas.authn.ldap[0].validateOnCheckout=false
cas.authn.ldap[0].validatePeriodically=false
```
results in an error

```
Error creating bean with name 'ldapAuthenticationConfiguration': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Validator configured, but no validate flag has been set
```
- CAS server version : 5.0.2

**Comment by Condor70** [comment] 2017-01-18 15:19
Duplicate of #2263

**Comment by mmoayyed** [comment] 2017-01-18 15:44
@maelstr if you do need it backported, please submit a pull request to the 5.0.x branch. Thanks!

**Closed** 2017-01-18 15:44 UTC
Labels: Already Fixed
