### ISSUE TITLE
Services management web app throws NPE after login

### ISSUE THREAD

**Issue by dima767** [apereo/cas#2593] opened 2017-05-03 15:58 UTC
```bash

   ____      _      ____      __  __                                                                     _   
  / ___|    / \    / ___|    |  \/  |   __ _   _ __     __ _    __ _    ___   _ __ ___     ___   _ __   | |_ 
 | |       / _ \   \___ \    | |\/| |  / _` | | '_ \   / _` |  / _` |  / _ \ | '_ ` _ \   / _ \ | '_ \  | __|
 | |___   / ___ \   ___) |   | |  | | | (_| | | | | | | (_| | | (_| | |  __/ | | | | | | |  __/ | | | | | |_ 
  \____| /_/   \_\ |____/    |_|  |_|  \__,_| |_| |_|  \__,_|  \__, |  \___| |_| |_| |_|  \___| |_| |_|  \__|
                                                               |___/                                         

CAS Version: 5.1.0-RC4
CAS Commit Id: 8aa6d4a91544847de8464e52a0fde3114ce94d66
CAS Build Date/Time: 2017-05-03T14:16:26Z
Spring Boot Version: 1.5.3.RELEASE
------------------------------------------------------------
System Date/Time: 2017-05-03T11:50:50.492
System Temp Directory: /opt/tomcat-cluster/apache-tomcat-8.0.32_node1/temp
------------------------------------------------------------
Java Home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Java Vendor: Oracle Corporation
Java Version: 1.8.0_121
JCE Installed: no
------------------------------------------------------------
OS Architecture: x86_64
OS Name: Mac OS X
OS Version: 10.12.4
------------------------------------------------------------
```

This is a fresh svc mgmt web app on top of freshly inited PostgreSQL (9.6) DB. After trying to access it, CAS login form is displayed and after successful login, the successful logout screen is displayed. The log shows the following:

```java
2017-05-03 11:53:02,877 ERROR [org.apereo.cas.mgmt.services.web.AbstractManagementController] - <null>
java.lang.NullPointerException: null
	at java.util.ArrayList.<init>(ArrayList.java:177) ~[?:1.8.0_121]
	at org.apereo.cas.mgmt.services.web.factory.AttributeFormDataPopulator.populateFormData(AttributeFormDataPopulator.java:34) ~[cas-management-webapp-support-5.1.0-RC4.jar:5.1.0-RC4]
	at org.apereo.cas.mgmt.services.web.factory.DefaultRegisteredServiceFactory.lambda$createFormData$0(DefaultRegisteredServiceFactory.java:47) ~[cas-management-webapp-support-5.1.0-RC4.jar:5.1.0-RC4]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_121]
	at org.apereo.cas.mgmt.services.web.factory.DefaultRegisteredServiceFactory.createFormData(DefaultRegisteredServiceFactory.java:47) ~[cas-management-webapp-support-5.1.0-RC4.jar:5.1.0-RC4]
	at org.apereo.cas.mgmt.services.web.RegisteredServiceSimpleFormController.getServiceById(RegisteredServiceSimpleFormController.java:98) ~[cas-management-webapp-support-5.1.0-RC4.jar:5.1.0-RC4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
...

```

**Comment by mmoayyed** [comment] 2017-05-03 16:02
Duplicate of https://github.com/apereo/cas/issues/2585 Switch to 5.1 SNAPSHOT please.

**Comment by dima767** [comment] 2017-05-03 16:02
In `RC5-SNAPSHOT`?

**Closed by mmoayyed** 2017-05-03 16:02 UTC
Labels: Bug, Management Webapp, Services

**Comment by mmoayyed** [comment] 2017-05-03 16:03
`5.1.0-SNAPSHOT` to be precise. Sorry, shoulda specified.

**Comment by dima767** [comment] 2017-05-03 16:04
Oh, that's right. There is no `RC5`

Will try that. Thank you!
